snapm: raise SnapmNotFoundError if source path does not exist
Currently Manager.create_snapshot_set() fails with FileNotFoundError
when a source path is non-existent:

ERROR - Command failed: [Errno 2] No such file or directory: '/not/a/mount/point'

FileNotFoundError: [Errno 2] No such file or directory: '/dev/fedora/nosuch'

Vs.

ERROR - No such file or directory: /not/a/mount/point
ERROR - Command failed: Source path '/not/a/mount/point' does not exist

SnapmNotFoundError: Source path '/not/a/mount/point' does not exist

Fixes: #118