lvm2: fix Snapshot initialisation after Lvm2Plugin.rename_snapshot()
The initialisation of the Snapshot object returned by
Lvm2Plugin.rename_snapshot() was incorrect: this leads to failures in
the test suite when a snapshot set is renamed and then deleted:

FAILED tests/test_command.py::CommandTests::test_rename_snapset - snapm._snap...
FAILED tests/test_manager.py::ManagerTests::test_rename_snapshot_set - snapm....

The wrong value was passed for the name, origin, and lv_name arguments
and the type of the returned value was the abstract Lvm2Snapshot rather
than Lvm2CowSnapshot or Lvm2ThinSnapshot.

Fix the arguments passed to the initialiser and delegate construction of
the snapshot object to a new _build_snapshot() method defined by
Lvm2CowSnapshot and Lvm2ThinSnapshot.