tests: update stratisd to stratisd-v3.8.5 and pin rust toolchain
Build errors have appeared in CI:

    error: unnecessary parentheses around closure body
      --> src/dbus_api/filesystem/prop_conv.rs:30:36
       |
    30 |     option_to_tuple(origin.map(|u| (uuid_to_string!(u))), String::new())
       |                                    ^                  ^
       |
       = note: `-D unused-parens` implied by `-D unused`
       = help: to override `-D unused` add `#[allow(unused_parens)]`
    help: remove these parentheses
       |
    30 -     option_to_tuple(origin.map(|u| (uuid_to_string!(u))), String::new())
    30 +     option_to_tuple(origin.map(|u| uuid_to_string!(u)), String::new())
       |

    error: could not compile `stratisd` (lib) due to 1 previous error
    make: *** [Makefile:121: build] Error 101
    Error: Process completed with exit code 2.

This appears to be a result of dtolnay/rust-toolchain@master moving up
to Rust 1.90.0: testing with the latest release and current development
toolchain (1.85.0) the build passes.

Resolves: #491

Signed-off-by: Bryn M. Reeves <bmr@redhat.com>