snapm: fix exception when reverting unmounted snapset
If a snapshot set is unmounted at the time of a revert operation the
merge of the snapshot volumes will proceed immediately: this causes an
exception when testing the 'snapset.mounted' property to determine
whether or not to display the "reboot required" warning message:

  Traceback (most recent call last):
    File "/root/src/git/snapm/bin/snapm", line 7, in <module>
      r = main(sys.argv)
    File "/root/src/git/snapm/snapm/command.py", line 1447, in main
      status = cmd_args.func(cmd_args)
    File "/root/src/git/snapm/snapm/command.py", line 792, in _revert_cmd
      snapset = revert_snapset(manager, name=name, uuid=uuid)
    File "/root/src/git/snapm/snapm/command.py", line 498, in revert_snapset
      return manager.revert_snapshot_set(name=name, uuid=uuid)
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
    File "/root/src/git/snapm/snapm/manager/_manager.py", line 974, in revert_snapshot_set
      if snapset.mounted:
         ^^^^^^^^^^^^^^^
    File "/root/src/git/snapm/snapm/_snapm.py", line 835, in mounted
      return self.snapshot_mounted or self.origin_mounted
             ^^^^^^^^^^^^^^^^^^^^^
    File "/root/src/git/snapm/snapm/_snapm.py", line 823, in snapshot_mounted
      return any(s.snapshot_mounted for s in self.snapshots)
    File "/root/src/git/snapm/snapm/_snapm.py", line 823, in <genexpr>
      return any(s.snapshot_mounted for s in self.snapshots)
                 ^^^^^^^^^^^^^^^^^^
    File "/root/src/git/snapm/snapm/_snapm.py", line 1075, in snapshot_mounted
      if self.status != SnapStatus.ACTIVE:
         ^^^^^^^^^^^
    File "/root/src/git/snapm/snapm/manager/plugins/lvm2.py", line 431, in status
      lv_dict = self._get_lv_dict_cache()
    File "/root/src/git/snapm/snapm/manager/plugins/lvm2.py", line 463, in _get_lv_dict_cache
      lvs_dict = get_lvs_json_report(f"{self.vg_name}/{self.lv_name}")
    File "/root/src/git/snapm/snapm/manager/plugins/lvm2.py", line 237, in get_lvs_json_report
      raise SnapmCalloutError(f"Error calling {LVS_CMD}: {err}") from err
  snapm._snapm.SnapmCalloutError: Error calling lvs: Command '['lvs', '--reportformat', 'json', '--units', 'b', '--options', 'vg_name,lv_name,lv_attr,origin,pool_lv,lv_size,data_percent,lv_role', 'fedora/test1-snapset_snapset1_1726773074_-mnt-test1']' returned non-zero exit status 5.

Save the mount status before issuing the revert operation to prevent
this.