fsdiff: tolerate missing python magic and work around Magic.close() bug
Since `magic` is not intended to be a hard dependency (it's not included
in `requirements.txt`), make the imports in `snapm.fsdiff` tolerate a
missing `magic` module. Check module availability in
`snapm.fsdiff.fsdiffer` so that we can let the user know before doing
anything expensive.

In addition, as a temporary workaround for rhbz#2419719 - TypeError:
'NoneType' object is not callable incmagic.close() - monkeypatch the
`magic` module to avoid this unpleasant output on process exit:

  root@f42-snapm-vm1:~/src/git/snapm# snapm snapset diff before-upgrade . -M never -s /etc -x "*etc/lvm*" --file-types
  Gathering paths from before-upgrade /etc: found 9604 paths
  Scanned 2919 paths in 0:00:03.048311 (excluded 6685)
  Gathering paths from System Root /etc: found 12384 paths
  Scanned 2923 paths in 0:00:02.603263 (excluded 9461)
  Found 23 differences in 0:00:00.021054
  Found 2 moves in 0:00:00.006530
  Built tree with 23 nodes
  /
  └── [*] etc
      ├── [*] dpkg
      │   └── [<] dpkg.cfg -> /etc/opt/dpkg.cfg
      ├── [*] fstab
      ├── [*] ld.so.cache
      ├── [<] moved.conf -> /etc/movedto.conf
      ├── [>] movedto.conf <- /etc/moved.conf
      ├── [+] newfile.conf
      ├── [*] opt
      │   └── [>] dpkg.cfg <- /etc/dpkg/dpkg.cfg
      ├── [+] quux
      │   └── [+] foo.conf
      ├── snapm
      │   ├── [*] plugins.d
      │   │   ├── [*] lvm2-cow.conf
      │   │   ├── [*] lvm2-thin.conf
      │   │   └── [*] stratis.conf
      │   └── [*] schedule.d
      │       └── [*] system-daily.json
      ├── [!] system-release
      ├── systemd
      │   └── [*] system
      │       └── [*] timers.target.wants
      └── [*] yum.repos.d
          └── [+] _copr:copr.fedorainfracloud.org:packit:snapshotmanager-snapm-843.repo
  Exception ignored in: <function MagicDetect.__del__ at 0x7f5b43bb3600>
  Traceback (most recent call last):
    File "/usr/lib/python3.13/site-packages/magic.py", line 308, in __del__
    File "/usr/lib/python3.13/site-packages/magic.py", line 135, in close
  TypeError: 'NoneType' object is not callable

Even if this has side effects like leaving magic resources around (it
shouldn't, and if it does, that's a `python-file-magic` bug), we don't
really care since our processes are short lived and this error pops up
during final garbage collection on exit anyway.

Resolves: #858

Signed-off-by: Bryn M. Reeves <bmr@redhat.com>